/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author nanda
 */
public class MPASDetails extends javax.swing.JFrame {

    /**
     * Creates new form MPASDetails
     */
    Connection con;
    Statement s;
    ResultSet rs;
    int totalTickets, maxWeeks;
    float avgOccupancy, revenue;
    public MPASDetails() {
        totalTickets = 0;
        maxWeeks = 0;
        avgOccupancy = 0;
        revenue = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpas", "root", "root");
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Database Error!");
            this.setVisible(false);
            this.dispose();
            System.exit(0);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allscroll = new javax.swing.JScrollPane();
        weeklylist = new javax.swing.JTable();
        totalscroll = new javax.swing.JScrollPane();
        totalstats = new javax.swing.JTable();
        datamovielabel = new javax.swing.JLabel();
        totallabel = new javax.swing.JLabel();
        otherbutton = new javax.swing.JButton();
        detailsarea = new java.awt.TextArea();
        totalcontent = new javax.swing.JLabel();
        movienamedetails = new javax.swing.JTextField();
        okbutton = new javax.swing.JButton();
        weeks = new javax.swing.JLabel();
        occ = new javax.swing.JLabel();
        tickets = new javax.swing.JLabel();
        rev = new javax.swing.JLabel();
        analysis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        weeklylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Week", "Occupancy %", "Tickets Sold", "Revenue"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        allscroll.setViewportView(weeklylist);

        totalstats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Weeks", "Occupancy %", "Tickets Sold", "Revenue", "Analysis"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        totalscroll.setViewportView(totalstats);

        datamovielabel.setText("Movie Name");

        totallabel.setText("Total");

        otherbutton.setText("Back");
        otherbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherbuttonActionPerformed(evt);
            }
        });

        detailsarea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        detailsarea.setEditable(false);

        okbutton.setText("OK");
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });

        weeks.setText("0");

        occ.setText("0");

        tickets.setText("0");

        rev.setText("0");

        analysis.setText("Analysis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(548, 548, 548)
                .addComponent(totalcontent, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(allscroll, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailsarea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalscroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(weeks, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(occ, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(otherbutton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tickets, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(rev, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(analysis, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(datamovielabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(movienamedetails, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(totallabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datamovielabel)
                    .addComponent(movienamedetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allscroll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailsarea, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totallabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalscroll, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(totalcontent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weeks)
                            .addComponent(occ)
                            .addComponent(tickets)
                            .addComponent(rev)
                            .addComponent(analysis, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otherbutton)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void otherbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new MPASEntry().setVisible(true);
    }//GEN-LAST:event_otherbuttonActionPerformed

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        // TODO add your handling code here:
        totalTickets = 0;
        maxWeeks = 0;
        avgOccupancy = 0;
        revenue = 0;
        detailsarea.setText("");
        try {
            s = con.createStatement();
            rs = s.executeQuery("select * from MovieData where name='"+movienamedetails.getText()+"';");
            if(!rs.first()) JOptionPane.showMessageDialog(this, "No such movie!");
            s = con.createStatement();
            rs = s.executeQuery("select * from MovieData where name='"+movienamedetails.getText()+"';");
            while(rs.next()) {
                detailsarea.append(rs.getString(2)+"\t\t"+rs.getString(3)+"\t    "+rs.getString(4)+"\t\t"+rs.getString(5)+"\n");
                maxWeeks = rs.getInt(2);
                avgOccupancy += rs.getFloat(3);
                totalTickets += rs.getInt(4);
                revenue += rs.getFloat(5);
            }
            avgOccupancy /= maxWeeks;
            weeks.setText(Integer.toString(maxWeeks));
            occ.setText(Float.toString(avgOccupancy));
            tickets.setText(Integer.toString(totalTickets));
            rev.setText(Float.toString(revenue));
            s = con.createStatement();
            rs = s.executeQuery("select analysis from MovieAnalysis where name='"+movienamedetails.getText()+"';");
            if(rs.first()) analysis.setText(rs.getString(1));
            else analysis.setText("-");
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }
    }//GEN-LAST:event_okbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane allscroll;
    private javax.swing.JLabel analysis;
    private javax.swing.JLabel datamovielabel;
    private java.awt.TextArea detailsarea;
    private javax.swing.JTextField movienamedetails;
    private javax.swing.JLabel occ;
    private javax.swing.JButton okbutton;
    private javax.swing.JButton otherbutton;
    private javax.swing.JLabel rev;
    private javax.swing.JLabel tickets;
    private javax.swing.JLabel totalcontent;
    private javax.swing.JLabel totallabel;
    private javax.swing.JScrollPane totalscroll;
    private javax.swing.JTable totalstats;
    private javax.swing.JTable weeklylist;
    private javax.swing.JLabel weeks;
    // End of variables declaration//GEN-END:variables
}
