/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author nanda
 */
public class MPASNewMovie extends javax.swing.JFrame {

    /**
     * Creates new form MPASUpdate
     */
    Connection con;
    Statement s;
    ResultSet rs;
    public MPASNewMovie() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpas", "root", "root");
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Database Error!");
            this.setVisible(false);
            this.dispose();
            System.exit(0);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Occupancy3 = new javax.swing.JTextField();
        TicketSold3 = new javax.swing.JTextField();
        week1label = new javax.swing.JLabel();
        Revenue3 = new javax.swing.JTextField();
        occlabel = new javax.swing.JLabel();
        ticketslabel = new javax.swing.JLabel();
        Occupancy4 = new javax.swing.JTextField();
        TicketSold4 = new javax.swing.JTextField();
        revenuelabel = new javax.swing.JLabel();
        Revenue4 = new javax.swing.JTextField();
        week2label = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        week3label = new javax.swing.JLabel();
        week4label = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        MovieName = new javax.swing.JTextField();
        EntryFormLabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        Occupancy1 = new javax.swing.JTextField();
        TicketSold1 = new javax.swing.JTextField();
        Occupancy2 = new javax.swing.JTextField();
        TicketSold2 = new javax.swing.JTextField();
        Revenue2 = new javax.swing.JTextField();
        Revenue1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        week1label.setText("Week - 1 ");

        occlabel.setText("Occupancy");

        ticketslabel.setText("Tickets Sold");

        revenuelabel.setText("Revenue");

        week2label.setText("Week - 2");

        Update.setText("Submit");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        week3label.setText("Week - 3");

        week4label.setText("Week - 4");

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        EntryFormLabel.setText("New Movie Details");

        namelabel.setText("Movie Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(week2label)
                            .addComponent(week1label)
                            .addComponent(week3label)
                            .addComponent(week4label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Occupancy1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Occupancy3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Occupancy4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Occupancy2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TicketSold1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(occlabel)
                                        .addGap(96, 96, 96)
                                        .addComponent(ticketslabel)
                                        .addGap(29, 29, 29))
                                    .addComponent(TicketSold2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TicketSold3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TicketSold4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Revenue2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Revenue3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Revenue4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Revenue1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(revenuelabel))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(namelabel)
                                .addGap(34, 34, 34)
                                .addComponent(MovieName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(EntryFormLabel)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(EntryFormLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel)
                    .addComponent(MovieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occlabel)
                    .addComponent(ticketslabel)
                    .addComponent(revenuelabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(week1label)
                    .addComponent(Occupancy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicketSold1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Revenue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(week2label)
                    .addComponent(Occupancy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicketSold2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Revenue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(week3label)
                    .addComponent(Occupancy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicketSold3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Revenue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(week4label)
                    .addComponent(Occupancy4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Revenue4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicketSold4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update)
                    .addComponent(Cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        try {
            if(MovieName.getText().equals("")) throw new Exception();
            s = con.createStatement();
            rs = s.executeQuery("select * from MovieData where name='"+MovieName.getText()+"';");
            try {
                if(rs.first()) throw new Exception();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Movie already exists!");
                flag = 1;
            }
            if(flag == 0) {
                if(!Occupancy1.getText().equals("")) {
                    s = con.createStatement();
                    s.execute("insert into MovieData values('"+MovieName.getText()+"', "+Integer.toString(1)+", "+Occupancy1.getText()+", "+TicketSold1.getText()+", "+Revenue1.getText()+");");
                }
                if(!Occupancy2.getText().equals("")) {
                    s = con.createStatement();
                    s.execute("insert into MovieData values('"+MovieName.getText()+"', "+Integer.toString(2)+", "+Occupancy2.getText()+", "+TicketSold2.getText()+", "+Revenue2.getText()+");");
                }
                if(!Occupancy3.getText().equals("")) {
                    s = con.createStatement();
                    s.execute("insert into MovieData values('"+MovieName.getText()+"', "+Integer.toString(3)+", "+Occupancy3.getText()+", "+TicketSold3.getText()+", "+Revenue3.getText()+");");
                }
                if(!Occupancy4.getText().equals("")) {
                    s = con.createStatement();
                    s.execute("insert into MovieData values('"+MovieName.getText()+"', "+Integer.toString(4)+", "+Occupancy4.getText()+", "+TicketSold4.getText()+", "+Revenue4.getText()+");");
                }
                JOptionPane.showMessageDialog(this, "Updated!");
            }
            this.setVisible(false);
            this.dispose();
            new MPASEntry().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Movie Error!");
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new MPASEntry().setVisible(true);
    }//GEN-LAST:event_CancelActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel EntryFormLabel;
    private javax.swing.JTextField MovieName;
    private javax.swing.JTextField Occupancy1;
    private javax.swing.JTextField Occupancy2;
    private javax.swing.JTextField Occupancy3;
    private javax.swing.JTextField Occupancy4;
    private javax.swing.JTextField Revenue1;
    private javax.swing.JTextField Revenue2;
    private javax.swing.JTextField Revenue3;
    private javax.swing.JTextField Revenue4;
    private javax.swing.JTextField TicketSold1;
    private javax.swing.JTextField TicketSold2;
    private javax.swing.JTextField TicketSold3;
    private javax.swing.JTextField TicketSold4;
    private javax.swing.JButton Update;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel occlabel;
    private javax.swing.JLabel revenuelabel;
    private javax.swing.JLabel ticketslabel;
    private javax.swing.JLabel week1label;
    private javax.swing.JLabel week2label;
    private javax.swing.JLabel week3label;
    private javax.swing.JLabel week4label;
    // End of variables declaration//GEN-END:variables
}
